name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pipeline/tests/unit/**') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pytest only
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run unit tests (sanitize_bio)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -q pipeline/tests/unit/test_enrich_company.py

  web-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run test:ci

  web-e2e-prod:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright (prod mode, Chromium)
        env:
          # E2E_USE_START handled inside script; set here if needed elsewhere
          E2E_USE_START: 'true'
        run: npm run e2e:prod:chromium
